openrouter.api.key=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

spring.datasource.url=jdbc:h2:mem:moviesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update